#app
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 8082
  error:
    include-message: always

#zuul
zuul:
  sensitive-headers: Cookie,Set-Cookie

#eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE}

#keycloak
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT}
  public-client: false
  principal-attribute: preferred_username
  credentials:
      secret: ${KEYCLOAK_CLIENT_SECRET}
