#app
spring:
  application:
    name: gateway-service

server:
  port: 8080
  error:
    include-message: always

#zuul
zuul:
  sensitive-headers: Cookie,Set-Cookie

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
