#app configs
spring:
  application:
    name: car-service
server:
  port: 8090
  error:
    include-message: always

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
