#app
spring:
  application:
    name: rental-request-service
server:
  port: 8092
  error:
    include-message: always

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
