#app
spring:
  application:
    name: user-service
server:
  port: 8099

#eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE}

#keycloak
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PASSWORD}
